# extends:
#   - "eslint:recommended"
#   - "plugin:@typescript-eslint/eslint-recommended"
#   - "plugin:@typescript-eslint/recommended"
#   - "prettier"
extends:
  - "airbnb-typescript"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  ecmaVersion: "latest"
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "import"
  - "jsx-a11y"
  - "prettier"
  - "react"
  - "react-hooks"
root: true
rules:
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: _
      varsIgnorePattern: _
  "import/extensions":
    - warn
    - never
    - pattern:
        - "json": "never"
      ignorePackages: true
